settings:
  name: "Product Name"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Cloud Volumes ONTAP 9.10.1 Release Notes
      url: /index.html
    - title: What's new
      url: /reference-new-9101.html
    - title: Licensing overview
      url: /concept-licensing-9101.html
    - title: Supported configurations
      entries:
        - title: AWS
          url: /reference-configs-aws-9101.html
        - title: Azure
          url: /reference-configs-azure-9101.html
        - title: GCP
          url: /reference-configs-gcp-9101.html
    - title: Storage limits
      entries:
        - title: AWS
          url: /reference-limits-aws-9101.html
        - title: Azure
          url: /reference-limits-azure-9101.html
        - title: GCP
          url: /reference-limits-gcp-9101.html
    - title: Known issues
      url: /reference-issues-9101.html
    - title: Known limitations
      entries:
        - title: Common limitations
          url: /reference-limitations-9101.html
        - title: Limitations in AWS
          url: /reference-limitations-aws-9101.html
        - title: Limitations in Azure
          url: /reference-limitations-azure-9101.html
        - title: Limitations in GCP
          url: /reference-limitations-gcp-9101.html
    - title: Cloud provider integrations
      url: /reference-provider-integrations-9101.html
    - title: Legal notices
      url: /reference-legal-notices.html
