settings:
  name: Cloud Volumes ONTAP 9.10.1 release notes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  versions:
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-relnotes
      version-number: "9.11.0"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9101-relnotes
      version-number: "9.10.1"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9100-relnotes
      version-number: "9.10.0"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-991-relnotes
      version-number: "9.9.1"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-9100-relnotes
      version-number: "9.9.0"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-98-relnotes
      version-number: "9.8"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-97-relnotes
      version-number: "9.7"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-96-relnotes
      version-number: "9.6"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-95-relnotes
      version-number: "9.5"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-94-relnotes
      version-number: "9.4"
    - name: Cloud Volumes ONTAP
      url: /cloud-volumes-ontap-93-relnotes
      version-number: "9.3"
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Release notes home
      url: /index.html
    - title: What's new
      url: /reference-new-9101.html
    - title: Licensing overview
      url: /concept-licensing-9101.html
    - title: Supported configurations
      entries:
        - title: AWS
          url: /reference-configs-aws-9101.html
        - title: Azure
          url: /reference-configs-azure-9101.html
        - title: GCP
          url: /reference-configs-gcp-9101.html
    - title: Storage limits
      entries:
        - title: AWS
          url: /reference-limits-aws-9101.html
        - title: Azure
          url: /reference-limits-azure-9101.html
        - title: GCP
          url: /reference-limits-gcp-9101.html
    - title: Known issues
      url: /reference-issues-9101.html
    - title: Known limitations
      entries:
        - title: Common limitations
          url: /reference-limitations-9101.html
        - title: Limitations in AWS
          url: /reference-limitations-aws-9101.html
        - title: Limitations in Azure
          url: /reference-limitations-azure-9101.html
        - title: Limitations in GCP
          url: /reference-limitations-gcp-9101.html
    - title: Cloud provider integrations
      url: /reference-provider-integrations-9101.html
    - title: Legal notices
      url: /reference-legal-notices.html
homepage:
  tiles:
    - title: Get started
      links:
        - title: What's new
          url: reference-new-9101.html
        - title: Licensing overview
          url: concept-licensing-9101.html
    - title: Amazon Web Services
      links:
        - title: Supported configurations
          url: reference-configs-aws-9101.html
        - title: Storage limits
          url: reference-limits-aws-9101.html
        - title: Limitations
          url: reference-limitations-gcp-9101.html
    - title: Google Cloud
      links:
        - title: Supported configurations
          url: reference-configs-gcp-9101.html
        - title: Storage limits
          url: reference-limits-gcp-9101.html
        - title: Limitations
          url: reference-limitations-gcp-9101.html
    - title: Microsoft Azure
      links:
        - title: Supported configurations
          url: reference-configs-azure-9101.html
        - title: Storage limits
          url: reference-limits-azure-9101.html
        - title: Limitations
          url: reference-limitations-azure-9101.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
